### ISSUE TITLE
Numbers not localized

### ISSUE THREAD

**Issue by MKleinSB** [PiSupply/pxt-iot-lora-node#12]
You forget to localize the numbers of Channels and Spreadingfactor.
![unbenannt](https://user-images.githubusercontent.com/37311672/48303543-9ca10780-e50b-11e8-9306-438416ac371d.png)

**Comment by ryanteck** [comment]
Currently looking at how to do this as the tutorial for makecode doesn't seem to show how to do this. I'll look at this tomorrow evening.

**Comment by ryanteck** [comment]
Been having a few issues with it not displaying despite adding what seems to be the correct string, going to label this as a requires help issue.

**Comment by ryanteck** [comment]
That fixed it, Thanks very much @MKleinSB
