### ISSUE TITLE
Needs new block and documentation for region changes

### ISSUE THREAD

**Issue by ryanteck** [PiSupply/pxt-iot-lora-node#19]
The new RAK firmware requires the block and documentation to be added for the changing of the regions.

Blocks should be
EU868
US915

And other regions as we need.

**Comment by ryanteck** [comment]
The block should now be complete. Testing and documentation is required.

**Comment by MKleinSB** [comment]
Sorry, when I load the extension in makecode it didn´t finish loading. When I  import main.ts in custom.ts it works fine!

**Comment by ryanteck** [comment]
Hmm! I'll try again

**Comment by ryanteck** [comment]
@MKleinSB I'm not having issues importing the extension myself. Which browser are you using and such?

**Comment by MKleinSB** [comment]
Just tested with other browsers on other machines: It´s a problem with firefox Quantum on Windows10 and Windows7.
Chrome and Edge works fine!
