### ISSUE TITLE
Not working with US915

### ISSUE THREAD

**Issue by ukscone** [PiSupply/pxt-iot-lora-node#29]
doesn't seem to be working (reliably) using US915 frequency.

**Comment by ryanteck** [comment]
Sorry about the delay into looking at this @ukscone .

I've got a 915Mhz Gateway setup and can replicate the issue so will start diagnosing. now.

**Comment by ryanteck** [comment]
Ok so it seems to be that the RAK811 is potentially broadcasting on 71 different channels of which will mean it won't work!

Looking into fixing it.

**Comment by ryanteck** [comment]
Diagnosed the issue. Also affects all nodes however as most others use OTAA the issue wasn't affecting.

**Comment by ryanteck** [comment]
Ok,

This should be working now.

If you can test it out. Adding the set region block above the normal one like attached.

![microbit-screenshot (20)](https://user-images.githubusercontent.com/1104745/62426323-2bc5ff00-b6db-11e9-90ae-f42313e5a4dd.png)

You'll need to update the library by clicking the javascript button, then explorer under the micro:bit image and click the refresh button like shown.

![Screenshot from 2019-08-04 17-13-55](https://user-images.githubusercontent.com/1104745/62426329-45674680-b6db-11e9-8fc5-26ff51ca02f6.png)

**Comment by ukscone** [comment]
there was an error on refreshing the extension. had to start a project from scratch and import the extension rather thna updating an existing project
![mbioterr2](https://user-images.githubusercontent.com/3171454/62428267-a5ef8700-b6cd-11e9-87e0-a1e6b0208ce4.PNG)
![mbioterr](https://user-images.githubusercontent.com/3171454/62428268-abe56800-b6cd-11e9-9ec0-4e5916a985f6.PNG)

**Comment by ryanteck** [comment]
Think I know what's caused this issue. Going to fix it (it'll likely break your new code though)

**Comment by ryanteck** [comment]
And commited.

You'll just need to re-add the initialisation block (the ABP connect) bock but your old code should also now work when refreshing it again.

**Comment by ukscone** [comment]
ok got this error on refresh which i think you know about. 

error: main.ts(8,13): error TS2551: Property 'InitialiseRadioABP' does not exist on type 'typeof IotLoRaNode'. Did you mean 'InitialiseRadioOTAA'?

i'll just redo stuff from scratch as that seems to work and these are just tiny bits of code

**Comment by ryanteck** [comment]
Yep. If you remove ABP or as mentioned above re-add just that block it should work fine.

**Comment by ukscone** [comment]
sorry for the delay, forgot to comment on here after telling you on twitter it seemed to be working. anyway it now seems to be working ok.

**Comment by ryanteck** [comment]
excellent!
