### ISSUE TITLE
Cayenne LPP All implementations

### ISSUE THREAD

**Issue by ryanteck** [PiSupply/pxt-iot-lora-node#36]
Type | IPSO | LPP | Hex | Data Size | Data Resolution per bit
-- | -- | -- | -- | -- | --
Digital Input | 3200 | 0 | 0 | 1 | 1
Digital Output | 3201 | 1 | 1 | 1 | 1
Analog Input | 3202 | 2 | 2 | 2 | 0.01 Signed
Analog Output | 3203 | 3 | 3 | 2 | 0.01 Signed
Illuminance Sensor | 3301 | 101 | 65 | 2 | 1 Lux Unsigned MSB
Presence Sensor | 3302 | 102 | 66 | 1 | 1
Temperature Sensor | 3303 | 103 | 67 | 2 | 0.1 °C Signed MSB
Humidity Sensor | 3304 | 104 | 68 | 1 | 0.5 % Unsigned
Accelerometer | 3313 | 113 | 71 | 6 | 0.001 G Signed MSB per axis
Barometer | 3315 | 115 | 73 | 2 | 0.1 hPa Unsigned MSB
Gyrometer | 3334 | 134 | 86 | 6 | 0.01 °/s Signed MSB per axis
GPS Location | 3336 | 136 | 88 | 9 | Latitude : 0.0001 ° Signed MSB Longitude : 0.0001 ° Signed MSB Altitude : 0.01 meter Signed MSB

**Comment by ryanteck** [comment]
Implementation List:

- [ ] Digital
- [ ] Analogue
- [ ] Illuminance
- [ ] Presence
- [ ] Temperature
- [ ] Humidity
- [ ] Accelerometer
- [ ] Barometer
- [ ] Gyrometer
- [ ] GPS
- [ ]

**Comment by marcusgrtz** [comment]
Personal ranking:

1. Barometer
2. Presence
3. Accelerometer
4. other

**Comment by marcusgrtz** [comment]
I believe Humidity is implemented wrong.
Data Size is defined as 1 Byte (UInt8_BE) and resolution is 0.5%

**Comment by marcusgrtz** [comment]
For reference see at my BME280 + LoRaNode code:
https://makecode.microbit.org/v1/52589-80461-63328-82780

**Comment by ryanteck** [comment]
I am getting there please give me a minute to test everything

**Comment by ryanteck** [comment]
Test List:
- [] Digital
- [] Analogue
- [] Illuminance
- [] Presence
- [] Temperature
- [] Humidity
- [] Accelerometer
- [] Barometer
- [] Gyrometer
- [] GPS

**Comment by ryanteck** [comment]
All are implemented now, needs some further testing but otherwise happy.

**Comment by marcusgrtz** [comment]
Thanks, Will try and test.
