### ISSUE TITLE
Will only write 3 to 6 values out of 10 to TTN

### ISSUE THREAD

**Issue by Svein-Tore** [PiSupply/pxt-iot-lora-node#42]
I have started to use the LoRa node for microbit.  I have created a program like this one in Makecode: 
  
 
![code](https://user-images.githubusercontent.com/16510390/79831576-f451cc80-83a7-11ea-8c4d-7d815a131297.JPG)

  
I assumed I then should get 10 values writtten in TTN, but I get only 3 to 6 values written (it varies from 3 to 6): 
![TTN_data](https://user-images.githubusercontent.com/16510390/79831663-22371100-83a8-11ea-9183-a1e6012ac219.JPG)
  
 
  
Any suggestions to what can be the problem? (I have also teseted the program without the set LoRa region block, but got the same result) 
  
Best wishes, 
  
Svein-Tore Gåsvik Narvestad

**Comment by Svein-Tore** [comment]
Hi Ryan!

 I have tested with 10000ms, but got the same problem.  I'm using gateway Dragino LG-01N  (https://www.dragino.com/products/lora/item/143-lg01n.html).

yes it is one channel and not what  I wanted. But it is almost impossible to get Pi Supplys IOT lora gateway phat today😢

Svein-Tore

**Comment by Svein-Tore** [comment]
Hi Ryan!
You are superb!  And this make sense. When I sent 10 packages it received 3-4, when I sent 20 it received 6-7, that is about 1/3. So since it switch between 3 channels,  I will theoretiacally get one third thru!   BTW it is no problem for me to wait a day or two 

NICE WORK Ryan!!

Best wishes, Svein-Tore

**Comment by ryanteck** [comment]
Hi @Svein-Tore , I'm working on this today.

Can I ask what frequency your SCG is configured to?

**Comment by Svein-Tore** [comment]
Hi Ryan!

The frequency is 868.1

**Comment by ryanteck** [comment]
Excellent. I'll be working on this today.

**Comment by Svein-Tore** [comment]
👍

**Comment by ryanteck** [comment]
Hi @Svein-Tore , I've implemented it however if you could test it and let me know that' be great.

You'll need to find this new block which is "EU Set Freq:" under the more blocks tab. You should get the ability to set to one of the 3 channels the node supports for EU, or back to al 3 frequencies.

![Screenshot from 2020-04-24 20-47-32](https://user-images.githubusercontent.com/1104745/80254875-de782c00-8673-11ea-9b84-e7ad5fa4e34b.png)

I tested it on my node and while on my 8 channel gateway we can see all the packets were on the same freq.

![microbit-screenshot (25)](https://user-images.githubusercontent.com/1104745/80254873-dddf9580-8673-11ea-87ca-14d44552a4d6.png)
![Screenshot from 2020-04-24 21-35-11](https://user-images.githubusercontent.com/1104745/80254867-dcae6880-8673-11ea-8b3d-df8b29ea9a78.png)

**Comment by ryanteck** [comment]
Oh, you might have to force update your library. To do this go to the Javascript tab, then at the side with the list of libraries click the re-load symbol, you'll need v0.1.37 or greater for it to work.
![Uploading Screenshot from 2020-04-24 21-40-55.png…]()

**Comment by Svein-Tore** [comment]
NICE!

I will take a look on it tomorrow!

**Comment by Svein-Tore** [comment]
Hi Ryan!

So I have tested and it works fine! Now  I get all the values, 

THANKS A LOT!!

**Comment by ryanteck** [comment]
Excellent glad to hear! I'll close this ticket now.
